[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
chainpaws = "GnEv5qz2xufNJqsqbkBvmgAa6ByWEmnygN6zayJ1SD8h"

[programs.devnet]
chainpaws = "GnEv5qz2xufNJqsqbkBvmgAa6ByWEmnygN6zayJ1SD8h"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "ts-node tests/chainpaws.ts"
